credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
cookie:
  expiry_days: 30
  key: fastmap_signature_key # Must be string
  name: fastmap_cookie_name
preauthorized:
  emails:
